# This has been stolen from https://github.com/marketplace/actions/emacs-lisp-check,
# as found in Sacha Chua's blog https://sachachua.com/blog/2020/06/2020-06-22-emacs-news/

name: Emacs Lisp check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-on-self:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        file: cperl-mode.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
