# This has been stolen from https://github.com/marketplace/actions/emacs-lisp-check,
# as found in Sacha Chua's blog https://sachachua.com/blog/2020/06/2020-06-22-emacs-news/

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
   runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    - uses: leotaku/elisp-check@master
      with:
        file: cperl--mode.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
